############# French navigation ##############

# main menu
[[main]]
name = "À propos"
url = "/about"
weight = 2

[[main]]
name = "Élements"
url = "/elements"
weight = 3


# footer menu
[[footer]]
name = "À propos"
url = "/about"
weight = 1

[[footer]]
name = "Élements"
url = "/elements"
weight = 2

[[footer]]
name = "Politique de confidentialité"
url = "/privacy-policy"
weight = 3
