apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: registry-secret
spec:
    secretTemplates:
        - name: image-pull-secret
          data:
            .dockerconfigjson: ENC[AES256_GCM,data:PrYIjkFYOYWYOEzWhUGI+Hcrsnv+EZUNNz1MmEElhwljIgFi8hUMcXV0KbOENKzUNuBweh3MBA06zqoTSbhB0eXFIQ54HYYN0up2wExANb9tPYtjLtep2271GylIv/TVWsjh1ExlARCixDPtLy8hw9FidlsLe81mPtsBuHeX+Vr2m/9Hgrj3Ov9Azf4=,iv:jn4VUUtEuUZbdoul5vKmTbsUnQYiWvQhriAwGs8URNg=,tag:R3MQwfL6//bPExE5whSeOw==,type:str]
          type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lc3vm7xf0e563t2rchm6wxa8lp2mrzecg2a0prldzt0z2ga7538qfpkwp6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdjRhMTU3ZDF6MTM1alBM
            T3NaMC9FeEJjenUxNDMySnJyZ3E0bXpXazJVCmIraG1CL25DZExoYVVRdUtlZkp5
            cHFoczNLSFNuaW5IVjZKVC9hSmgyTkkKLS0tIGdaK25Sc1FHcU9iSTZ5aXZKNG1V
            Q3EzMlpxK2I0QkV5T1JzbGRtL0lmdkEKRJ3abqC1KE6IaYo4P4wUN6CslXy3zJBk
            cyH6oQOoF/v1nLg/0H1zume93iZxYVRXIQOmcO6pgTCbDd2t5sOHjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T19:29:51Z"
    mac: ENC[AES256_GCM,data:3P3agXP/9eNwE41pugr12Y0NsL7RLq01887BuBVdPkhlwCnIkdw8rVN2zJNM5cjniA51QrCeEI7MJ3PeRjkx+7L1+3X6tuFd5JMhG8QXJBiJHg2dvnbr1ERZ/JxVlchogMvxhMdnzWoh1RQuIrMt3bQ69gK4ogzEDiAB7dBAdbY=,iv:boPNgi0mFtWXqOuk8ycUA3bm1AtBE+WEAcVOZ3ccxpY=,tag:kTT1BveZcpwFRMVG7eEgSA==,type:str]
    pgp:
        - created_at: "2025-01-07T19:29:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9GztP6xR+tEAQv/eUQrsUYM9FOynbDP0RREQGg7imaHRYNmQ52ARguamnmj
            /250MOpd+7PXuVu5bmxWW8jeiJ2VTY06N4hhpPwu/NmV+TCv0bcTCiC1SYX5mLKm
            SQDll3hD6PZNd2VXy2hPFnJEJ6EfERBu65FsXGU+P0NKL3LG6EkfcQSfZlN4Gs7m
            3DLoXB05Ngb9me7Vt6pTtSvdULDi4s9tO/Fb2zVfQ7QeqPMAUiCiYTXR6bba9j1m
            uJEiEITlKajPpXkmil+Plg3+NFlMDgI5apnJZ6914GJeuYcruuAVwws3qWsPJnxT
            XjT9IKCqTthVEn5q7NizWjjrG+1DbdZfd/Wmdl82ZfxjRA3ebtjaMVQmnkVhiAAf
            FSuqQa1mu75raM89vRuNobuDA/mJexc9xUO4GCC6A7sYNLZBvC8xUfCWCy9Ttkv/
            OaCMMs11vRVAhdn1qT0XSswQabxBD+o5XnWF7CjoGLme5Y8ZV/pNUQvcUEwgkSyY
            mVkRJPNgTUugCj3yCk780l4B9nhSQ0dfmMogXqwvrw3LOLSWibTC0aFYv0K2uICN
            HxAdK5J25JhzDmniouYYcedF2xUKv/Y38nXVgRsc1AXG/byXQ1i4KIUDK9UupLV9
            e1bDqZBU8o+tOGtBNn46
            =9EIx
            -----END PGP MESSAGE-----
          fp: 4DD454CA8F2056D5F0B7467841E83C8C6C68AC19
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
