apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: registry-secret
spec:
    secretTemplates:
        - name: image-pull-secret
          data:
            .dockerconfigjson: ENC[AES256_GCM,data:QlZ4sgR5mEOhNCtJPrXxRtSxrQ8dCla92kmkMlIG6vOf9/dhDoc4/8KPe9G4vplnHmlpaU7rPYNNpyrvOaNyU6vsN0cFpsIbwLf/hjPWIlLp0VEFY7h+vLneycwwJxlFqVLaG+ncOXA8JdBsYjwnbJy9t2gJI2Taji9aXxbwIyOJCy8KmAh9wuAUnPc=,iv:W0mFzaXG7LToZEpHjOEEpuzvXq7kaSSE61WHj74AYG8=,tag:03IvDxgTtce+mxuZBVHXvA==,type:str]
          type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1pmf2f6w55hvf98ly0cx4hv5gl23dx3s9fepqudezde565cjz7gys9xh2h4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc3JUMXB2Mkc5Y0s5aGNk
            UzBpbHQyazRNWVV3VWRNUXdYVHNKZk1kNm5NCjJkRmtlN3h4b25jc2pyb3NXaUFl
            czl1cUt3dkNMcjRKV21mWkZqalJDUjgKLS0tIFpBRXNVU0VPRFgzQWh0SHpwaWY5
            WktIWE9sdVFGRDZUVkxmUXI1bUJDb0EKtvZbgFGuhrd316nJW6OYHTEQ8C/6X3qO
            7hd8s6dAApqCsUMYMldVfpDe8FTUyuUsSsJIi++KYZyrfDasPGfREg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T20:53:21Z"
    mac: ENC[AES256_GCM,data:KZdgIGDQfxH4f2/zuMDaBMxjfb4eVEjbQuDuapkKgnY8hQsnK97zZNM8XcNqTF1lqfNmz/meJ1I4lmfyY5a4yHJ3gvOTRBfXo1LipHDpFevHfjNauTmlaBm/ZIMnEr/IUoWpsmwNmmMrJ7vAKaMpJVpdez5i98q/8QEe0dkgXUQ=,iv:Fu4HYyQlFQoTas413jiPDfBQgXDH7E4GHT3NFQFzNhE=,tag:yKYorLPptrXdxDIqdAPjvw==,type:str]
    pgp:
        - created_at: "2025-06-01T20:53:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9GztP6xR+tEAQwA1nsVhXaqhhtNlBdX5Q1QTY3FysBBck7Giv2sesT/s5vt
            7z9VtI5vpJx9/5zVH1K5yeaW1W5EOYAGBRAbGPvsRF2P1H7Jgz2Dw2htBY7qKnPb
            iC/Wwy3DPSHRcMdMlgs/KT8i7WiPpe4VZEEUaLYaexPCywF4ZifbCkRsKZwh8jkD
            j97hKZDlzjoVaPkIEzVbBPJbAEKIRwP91n+mPLPOXZkYBgUbtw+bupdnEKKks79/
            VtJ49FCt1eJVC6tG6wAursUsOcH8dVaYmMfsPTqW4WOExf1TCw8Jp3J6Z3KI09ye
            62i2Ye6T+qBmzrU2imjq/jrLRKCLLY5Ap43eFPDcY/J+5dc/o7PSSraTH8AdC4dB
            mTCvxKATZadeF1tCpv0ayAwP/UJOWFuki4f+zOrUzr1dr8NkMRknHEgimJ9alutL
            ASDhz9YQkb4mPbmHSX+l4fwhmJNeobCnUywaUclYt3VH4oiMqVWTZxUb504ajy2i
            XWGQfJI3VGdKsTqLty2l0l4BzGdrX4Pe5k8pLK8gbfftSjAVtYihtD9HiPOXac/2
            KD/pXdMBAgB4zP8BJ6J+LhZyC/yT8T87hchMBhhnlLnZXnnX9DQJby5k7cpvybZI
            eJBLv0eMGH5qfUKd9nbX
            =31As
            -----END PGP MESSAGE-----
          fp: 4DD454CA8F2056D5F0B7467841E83C8C6C68AC19
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
