name: Deploy Hugo Blog to Kubernetes

on:
  push:
    branches:
      - main # Déclencher lors des pushes sur la branche main

jobs:
  build-and-deploy:
    name: Build and Deploy to Kubernetes
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: registry.bastian-somon.fr/blog # Remplace <username> par ton utilisateur GitHub ou Docker Hub
      KUBE_NAMESPACE: blog # Nom de l'espace Kubernetes
      CHART_NAME: blog

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.bastian-somon.fr
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate to Kubernetes Cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy with Helm
        run: |
          cat $PWD/kubeconfig.yaml
          helm upgrade --install $CHART_NAME infra \
            --namespace $KUBE_NAMESPACE \
            --create-namespace
